package com.crosspay.payment.model;

import java.io.UnsupportedEncodingException;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.sql.Blob;
import java.util.Date;

import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;

import org.json.JSONException;
import org.json.JSONObject;

@Entity
@Table(name = "BENEFICIARY")
public class Beneficiary {

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int BENEFICIARY_ID;

	@NotNull
	private String CUSTOMERNO;

	@NotNull
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int BENEFICIARYNO;

	@NotNull
	private String BENEFICIARYFIRSTNAME;

	@Null
	private String BENEFICIARYMIDDLENAME;

	@NotNull
	private String BENEFICIARYLASTNAME;

	@Null
	private String BENEFICIARYPOBOX;

	@Null
	private String BENEFICIARYADDRESS1;

	@Null
	private String BENEFICIARYADDRESS2;

	@Null
	private String BENEFICIARYADDRESSCITY;

	@Null
	private String BENEFICIARYADDRESSSTATE;

	@Null
	private String BENEFICIARYADDRESSCOUNTRYCODE;

	@Null
	private String BENEFICIARYADDRESSZIP;

	@Null
	private String BENEFICIARYPHONE;

	@Null
	private String BENEFICIARYMOBILE;

	@NotNull
	private String BENEFICIARYEMAIL;

	@NotNull
	private int BENEFICIARYSTATUS;

	@Null
	private String BENEFICIARYFAVOURITE;

	@NotNull
	private String BENEFICIARYGENDER;

	@Null
	private String NOTIFYBENEBYEMAIL;

	@Null
	private String NOTIFYBENEBYSMS;
	
	@Null
	private String DATEOFBIRTH;

	@NotNull
	private Date CREATEDON;

	@Null
	 private Blob IMAGE;
	
	// Public methods
	// Getter and setter methods

	public int getBENEFICIARY_ID() {
		return BENEFICIARY_ID;
	}

	public void setBENEFICIARY_ID(int bENEFICIARY_ID) {
		BENEFICIARY_ID = bENEFICIARY_ID;
	}

	public String getCUSTOMERNO() {
		return CUSTOMERNO;
	}

	public void setCUSTOMERNO(String cUSTOMERNO) {
		CUSTOMERNO = cUSTOMERNO;
	}

	public int getBENEFICIARYNO() {
		return BENEFICIARYNO;
	}

	public void setBENEFICIARYNO(int bENEFICIARYNO) {
		BENEFICIARYNO = bENEFICIARYNO;
	}

	public String getBENEFICIARYFIRSTNAME() {
		return BENEFICIARYFIRSTNAME;
	}

	public void setBENEFICIARYFIRSTNAME(String bENEFICIARYFIRSTNAME) {
		BENEFICIARYFIRSTNAME = bENEFICIARYFIRSTNAME;
	}

	public String getBENEFICIARYMIDDLENAME() {
		return BENEFICIARYMIDDLENAME;
	}

	public void setBENEFICIARYMIDDLENAME(String bENEFICIARYMIDDLENAME) {
		BENEFICIARYMIDDLENAME = bENEFICIARYMIDDLENAME;
	}

	public String getBENEFICIARYLASTNAME() {
		return BENEFICIARYLASTNAME;
	}

	public void setBENEFICIARYLASTNAME(String bENEFICIARYLASTNAME) {
		BENEFICIARYLASTNAME = bENEFICIARYLASTNAME;
	}

	public String getBENEFICIARYPOBOX() {
		return BENEFICIARYPOBOX;
	}

	public void setBENEFICIARYPOBOX(String bENEFICIARYPOBOX) {
		BENEFICIARYPOBOX = bENEFICIARYPOBOX;
	}

	public String getBENEFICIARYADDRESS1() {
		return BENEFICIARYADDRESS1;
	}

	public void setBENEFICIARYADDRESS1(String bENEFICIARYADDRESS1) {
		BENEFICIARYADDRESS1 = bENEFICIARYADDRESS1;
	}

	public String getBENEFICIARYADDRESS2() {
		return BENEFICIARYADDRESS2;
	}

	public void setBENEFICIARYADDRESS2(String bENEFICIARYADDRESS2) {
		BENEFICIARYADDRESS2 = bENEFICIARYADDRESS2;
	}

	public String getBENEFICIARYADDRESSCITY() {
		return BENEFICIARYADDRESSCITY;
	}

	public void setBENEFICIARYADDRESSCITY(String bENEFICIARYADDRESSCITY) {
		BENEFICIARYADDRESSCITY = bENEFICIARYADDRESSCITY;
	}

	public String getBENEFICIARYADDRESSSTATE() {
		return BENEFICIARYADDRESSSTATE;
	}

	public void setBENEFICIARYADDRESSSTATE(String bENEFICIARYADDRESSSTATE) {
		BENEFICIARYADDRESSSTATE = bENEFICIARYADDRESSSTATE;
	}

	public String getBENEFICIARYADDRESSCOUNTRYCODE() {
		return BENEFICIARYADDRESSCOUNTRYCODE;
	}

	public void setBENEFICIARYADDRESSCOUNTRYCODE(String bENEFICIARYADDRESSCOUNTRYCODE) {
		BENEFICIARYADDRESSCOUNTRYCODE = bENEFICIARYADDRESSCOUNTRYCODE;
	}

	public String getBENEFICIARYADDRESSZIP() {
		return BENEFICIARYADDRESSZIP;
	}

	public void setBENEFICIARYADDRESSZIP(String bENEFICIARYADDRESSZIP) {
		BENEFICIARYADDRESSZIP = bENEFICIARYADDRESSZIP;
	}

	public String getBENEFICIARYPHONE() {
		return BENEFICIARYPHONE;
	}

	public void setBENEFICIARYPHONE(String bENEFICIARYPHONE) {
		BENEFICIARYPHONE = bENEFICIARYPHONE;
	}

	public String getBENEFICIARYMOBILE() {
		return BENEFICIARYMOBILE;
	}

	public void setBENEFICIARYMOBILE(String bENEFICIARYMOBILE) {
		BENEFICIARYMOBILE = bENEFICIARYMOBILE;
	}

	public String getBENEFICIARYEMAIL() {
		return BENEFICIARYEMAIL;
	}

	public void setBENEFICIARYEMAIL(String bENEFICIARYEMAIL) {
		BENEFICIARYEMAIL = bENEFICIARYEMAIL;
	}

	public int getBENEFICIARYSTATUS() {
		return BENEFICIARYSTATUS;
	}

	public void setBENEFICIARYSTATUS(int bENEFICIARYSTATUS) {
		BENEFICIARYSTATUS = bENEFICIARYSTATUS;
	}

	public String getBENEFICIARYFAVOURITE() {
		return BENEFICIARYFAVOURITE;
	}

	public void setBENEFICIARYFAVOURITE(String bENEFICIARYFAVOURITE) {
		BENEFICIARYFAVOURITE = bENEFICIARYFAVOURITE;
	}

	public String getBENEFICIARYGENDER() {
		return BENEFICIARYGENDER;
	}

	public void setBENEFICIARYGENDER(String bENEFICIARYGENDER) {
		BENEFICIARYGENDER = bENEFICIARYGENDER;
	}

	public String getNOTIFYBENEBYEMAIL() {
		return NOTIFYBENEBYEMAIL;
	}

	public void setNOTIFYBENEBYEMAIL(String nOTIFYBENEBYEMAIL) {
		NOTIFYBENEBYEMAIL = nOTIFYBENEBYEMAIL;
	}

	public String getNOTIFYBENEBYSMS() {
		return NOTIFYBENEBYSMS;
	}

	public void setNOTIFYBENEBYSMS(String nOTIFYBENEBYSMS) {
		NOTIFYBENEBYSMS = nOTIFYBENEBYSMS;
	}

	public Date getCREATEDON() {
		return CREATEDON;
	}

	public void setCREATEDON(Date cREATEDON) {
		CREATEDON = cREATEDON;
	}

	public String getDATEOFBIRTH() {
		return DATEOFBIRTH;
	}

	public void setDATEOFBIRTH(String dATEOFBIRTH) {
		DATEOFBIRTH = dATEOFBIRTH;
	}

	public Blob getIMAGE() {
		return IMAGE;
	}

	public void setIMAGE(Blob iMAGE) {
		IMAGE = iMAGE;
	}
	
	

}