package com.crosspay.payment.model;

import java.io.UnsupportedEncodingException;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.sql.Blob;
import java.util.Date;

import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;

import org.json.JSONException;
import org.json.JSONObject;

@Entity
@Table(name = "BENEFICIARYBANK")
public class BeneficiaryBank {

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int BENEFICIARYBANK_ID;

	@NotNull
	private String CUSTOMERNO;

	@NotNull
	private int BENEFICIARYNO;

	@Null
	private String BENEFICIARYACCOUNTNAME;

	@Null
	private String BENEFICIARYBANKCODE;

	@Null
	private String BENEFICIARYBANKNAME;

	@Null
	private String BENEFICIARYBANKACCOUNTNO;

	@Null
	private String SWIFTIFSC;

	@Null
	private String BENEFICIARYACCOUNTCCYCODE;

	@NotNull
	private int RECORDSTATUS;

	@NotNull
	private Date CREATEDON;
	
	@NotNull
	private int BANKTYPE;
	
	@Null
	private String BENEFICIARYBRANCHNAME;

	// Public methods
	// Getter and setter methods

	public int getBENEFICIARYBANK_ID() {
		return BENEFICIARYBANK_ID;
	}

	public void setBENEFICIARYBANK_ID(int bENEFICIARYBANK_ID) {
		BENEFICIARYBANK_ID = bENEFICIARYBANK_ID;
	}

	public String getCUSTOMERNO() {
		return CUSTOMERNO;
	}

	public void setCUSTOMERNO(String cUSTOMERNO) {
		CUSTOMERNO = cUSTOMERNO;
	}

	public int getBENEFICIARYNO() {
		return BENEFICIARYNO;
	}

	public void setBENEFICIARYNO(int bENEFICIARYNO) {
		BENEFICIARYNO = bENEFICIARYNO;
	}

	public String getBENEFICIARYACCOUNTNAME() {
		return BENEFICIARYACCOUNTNAME;
	}

	public void setBENEFICIARYACCOUNTNAME(String bENEFICIARYACCOUNTNAME) {
		BENEFICIARYACCOUNTNAME = bENEFICIARYACCOUNTNAME;
	}

	public String getBENEFICIARYBANKCODE() {
		return BENEFICIARYBANKCODE;
	}

	public void setBENEFICIARYBANKCODE(String bENEFICIARYBANKCODE) {
		BENEFICIARYBANKCODE = bENEFICIARYBANKCODE;
	}

	public String getBENEFICIARYBANKNAME() {
		return BENEFICIARYBANKNAME;
	}

	public void setBENEFICIARYBANKNAME(String bENEFICIARYBANKNAME) {
		BENEFICIARYBANKNAME = bENEFICIARYBANKNAME;
	}

	public String getBENEFICIARYBANKACCOUNTNO() {
		return BENEFICIARYBANKACCOUNTNO;
	}

	public void setBENEFICIARYBANKACCOUNTNO(String bENEFICIARYBANKACCOUNTNO) {
		BENEFICIARYBANKACCOUNTNO = bENEFICIARYBANKACCOUNTNO;
	}

	public String getSWIFTIFSC() {
		return SWIFTIFSC;
	}

	public void setSWIFTIFSC(String sWIFTIFSC) {
		SWIFTIFSC = sWIFTIFSC;
	}

	public String getBENEFICIARYACCOUNTCCYCODE() {
		return BENEFICIARYACCOUNTCCYCODE;
	}

	public void setBENEFICIARYACCOUNTCCYCODE(String bENEFICIARYACCOUNTCCYCODE) {
		BENEFICIARYACCOUNTCCYCODE = bENEFICIARYACCOUNTCCYCODE;
	}

	public int getRECORDSTATUS() {
		return RECORDSTATUS;
	}

	public void setRECORDSTATUS(int rECORDSTATUS) {
		RECORDSTATUS = rECORDSTATUS;
	}

	public Date getCREATEDON() {
		return CREATEDON;
	}

	public void setCREATEDON(Date cREATEDON) {
		CREATEDON = cREATEDON;
	}

	public int getBANKTYPE() {
		return BANKTYPE;
	}

	public void setBANKTYPE(int bANKTYPE) {
		BANKTYPE = bANKTYPE;
	}

	public String getBENEFICIARYBRANCHNAME() {
		return BENEFICIARYBRANCHNAME;
	}

	public void setBENEFICIARYBRANCHNAME(String bENEFICIARYBRANCHNAME) {
		BENEFICIARYBRANCHNAME = bENEFICIARYBRANCHNAME;
	}
	
	

}