package com.crosspay.payment.model;

import java.io.UnsupportedEncodingException;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.sql.Blob;
import java.util.Date;

import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;

import org.json.JSONException;
import org.json.JSONObject;

@Entity
@Table(name = "CPAGENTS")
public class CPAgents {

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int CPAGENTTD;

	@Null
	@Column(length = 12)
	private String AGENTCODE;

	@Null
	@Column(length = 120)
	private String AGENTNAME;

	@Null
	@Column(length = 3)
	private String AGENTCOUNTRYCODE;

	@Null
	@Column(length = 3)
	private String PAYOUTCURRENCYCODE;

	@Null
	@Column(precision = 15, scale = 3)
	private double PAYOUTMAXLIMIT;

	@Null
	private String COUNTRYNAME;

	@NotNull
	private int RECORDSTATUS;

	// Public methods
	// Getter and setter methods

	public int getCPAGENTTD() {
		return CPAGENTTD;
	}

	public void setCPAGENTTD(int cPAGENTTD) {
		CPAGENTTD = cPAGENTTD;
	}

	public String getAGENTCODE() {
		return AGENTCODE;
	}

	public void setAGENTCODE(String aGENTCODE) {
		AGENTCODE = aGENTCODE;
	}

	public String getAGENTNAME() {
		return AGENTNAME;
	}

	public void setAGENTNAME(String aGENTNAME) {
		AGENTNAME = aGENTNAME;
	}

	public String getAGENTCOUNTRYCODE() {
		return AGENTCOUNTRYCODE;
	}

	public void setAGENTCOUNTRYCODE(String aGENTCOUNTRYCODE) {
		AGENTCOUNTRYCODE = aGENTCOUNTRYCODE;
	}

	public String getPAYOUTCURRENCYCODE() {
		return PAYOUTCURRENCYCODE;
	}

	public void setPAYOUTCURRENCYCODE(String pAYOUTCURRENCYCODE) {
		PAYOUTCURRENCYCODE = pAYOUTCURRENCYCODE;
	}

	public double getPAYOUTMAXLIMIT() {
		return PAYOUTMAXLIMIT;
	}

	public void setPAYOUTMAXLIMIT(double pAYOUTMAXLIMIT) {
		PAYOUTMAXLIMIT = pAYOUTMAXLIMIT;
	}

	public String getCOUNTRYNAME() {
		return COUNTRYNAME;
	}

	public void setCOUNTRYNAME(String cOUNTRYNAME) {
		COUNTRYNAME = cOUNTRYNAME;
	}

	public int getRECORDSTATUS() {
		return RECORDSTATUS;
	}

	public void setRECORDSTATUS(int rECORDSTATUS) {
		RECORDSTATUS = rECORDSTATUS;
	}

}