package com.crosspay.payment.model;

public class CPSenderReceiver {

	private String CPSENDERRECEIVERID;

	private String TXNNO;

	private String CUSTOMERNO;

	private int BENEFICIARYNO;

	private String BENEFICIARYFIRSTNAME;

	private String BENEFICIARYMIDDLENAME;

	private String BENEFICIARYLASTNAME;

	private String BENEFICIARYPOBOX;

	private String BENEFICIARYADDRESS1;

	private String BENEFICIARYADDRESS2;

	private String BENEFICIARYADDRESSCITY;

	private String BENEFICIARYADDRESSSTATE;

	private String BENEFICIARYADDRESSCOUNTRYCODE;

	private String BENEFICIARYADDRESSZIP;

	private String BENEFICIARYPHONE;

	private String BENEFICIARYMOBILE;

	private String BENEFICIARYEMAIL;
	
	private String ORDERID;

	public String getCPSENDERRECEIVERID() {
		return CPSENDERRECEIVERID;
	}

	public void setCPSENDERRECEIVERID(String cPSENDERRECEIVERID) {
		CPSENDERRECEIVERID = cPSENDERRECEIVERID;
	}

	public String getTXNNO() {
		return TXNNO;
	}

	public void setTXNNO(String tXNNO) {
		TXNNO = tXNNO;
	}

	public String getCUSTOMERNO() {
		return CUSTOMERNO;
	}

	public void setCUSTOMERNO(String cUSTOMERNO) {
		CUSTOMERNO = cUSTOMERNO;
	}

	public int getBENEFICIARYNO() {
		return BENEFICIARYNO;
	}

	public void setBENEFICIARYNO(int bENEFICIARYNO) {
		BENEFICIARYNO = bENEFICIARYNO;
	}

	public String getBENEFICIARYFIRSTNAME() {
		return BENEFICIARYFIRSTNAME;
	}

	public void setBENEFICIARYFIRSTNAME(String bENEFICIARYFIRSTNAME) {
		BENEFICIARYFIRSTNAME = bENEFICIARYFIRSTNAME;
	}

	public String getBENEFICIARYMIDDLENAME() {
		return BENEFICIARYMIDDLENAME;
	}

	public void setBENEFICIARYMIDDLENAME(String bENEFICIARYMIDDLENAME) {
		BENEFICIARYMIDDLENAME = bENEFICIARYMIDDLENAME;
	}

	public String getBENEFICIARYLASTNAME() {
		return BENEFICIARYLASTNAME;
	}

	public void setBENEFICIARYLASTNAME(String bENEFICIARYLASTNAME) {
		BENEFICIARYLASTNAME = bENEFICIARYLASTNAME;
	}

	public String getBENEFICIARYPOBOX() {
		return BENEFICIARYPOBOX;
	}

	public void setBENEFICIARYPOBOX(String bENEFICIARYPOBOX) {
		BENEFICIARYPOBOX = bENEFICIARYPOBOX;
	}

	public String getBENEFICIARYADDRESS1() {
		return BENEFICIARYADDRESS1;
	}

	public void setBENEFICIARYADDRESS1(String bENEFICIARYADDRESS1) {
		BENEFICIARYADDRESS1 = bENEFICIARYADDRESS1;
	}

	public String getBENEFICIARYADDRESS2() {
		return BENEFICIARYADDRESS2;
	}

	public void setBENEFICIARYADDRESS2(String bENEFICIARYADDRESS2) {
		BENEFICIARYADDRESS2 = bENEFICIARYADDRESS2;
	}

	public String getBENEFICIARYADDRESSCITY() {
		return BENEFICIARYADDRESSCITY;
	}

	public void setBENEFICIARYADDRESSCITY(String bENEFICIARYADDRESSCITY) {
		BENEFICIARYADDRESSCITY = bENEFICIARYADDRESSCITY;
	}

	public String getBENEFICIARYADDRESSSTATE() {
		return BENEFICIARYADDRESSSTATE;
	}

	public void setBENEFICIARYADDRESSSTATE(String bENEFICIARYADDRESSSTATE) {
		BENEFICIARYADDRESSSTATE = bENEFICIARYADDRESSSTATE;
	}

	public String getBENEFICIARYADDRESSCOUNTRYCODE() {
		return BENEFICIARYADDRESSCOUNTRYCODE;
	}

	public void setBENEFICIARYADDRESSCOUNTRYCODE(String bENEFICIARYADDRESSCOUNTRYCODE) {
		BENEFICIARYADDRESSCOUNTRYCODE = bENEFICIARYADDRESSCOUNTRYCODE;
	}

	public String getBENEFICIARYADDRESSZIP() {
		return BENEFICIARYADDRESSZIP;
	}

	public void setBENEFICIARYADDRESSZIP(String bENEFICIARYADDRESSZIP) {
		BENEFICIARYADDRESSZIP = bENEFICIARYADDRESSZIP;
	}

	public String getBENEFICIARYPHONE() {
		return BENEFICIARYPHONE;
	}

	public void setBENEFICIARYPHONE(String bENEFICIARYPHONE) {
		BENEFICIARYPHONE = bENEFICIARYPHONE;
	}

	public String getBENEFICIARYMOBILE() {
		return BENEFICIARYMOBILE;
	}

	public void setBENEFICIARYMOBILE(String bENEFICIARYMOBILE) {
		BENEFICIARYMOBILE = bENEFICIARYMOBILE;
	}

	public String getBENEFICIARYEMAIL() {
		return BENEFICIARYEMAIL;
	}

	public void setBENEFICIARYEMAIL(String bENEFICIARYEMAIL) {
		BENEFICIARYEMAIL = bENEFICIARYEMAIL;
	}

	public String getORDERID() {
		return ORDERID;
	}

	public void setORDERID(String oRDERID) {
		ORDERID = oRDERID;
	}
	
	

}
