package com.crosspay.payment.model;

import java.io.UnsupportedEncodingException;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.sql.Blob;
import java.util.Date;

import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;

import org.json.JSONException;
import org.json.JSONObject;

@Entity
@Table(name = "CURRENCY")
public class Currency {

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int CURRENCY_ID;

	@NotNull
	private String CCYCODE;

	@Null
	private String CCYNAME;

	@Null
	private String CCYCOINNAME;

	@NotNull
	private int CCYROUNDINGNO;

	@NotNull
	private int CCYSTATUS;

	@NotNull
	private Date RECORDDATE;

	// Public methods
	// Getter and setter methods

	public int getCURRENCY_ID() {
		return CURRENCY_ID;
	}

	public void setCURRENCY_ID(int cURRENCY_ID) {
		CURRENCY_ID = cURRENCY_ID;
	}

	public String getCCYCODE() {
		return CCYCODE;
	}

	public void setCCYCODE(String cCYCODE) {
		CCYCODE = cCYCODE;
	}

	public String getCCYNAME() {
		return CCYNAME;
	}

	public void setCCYNAME(String cCYNAME) {
		CCYNAME = cCYNAME;
	}

	public String getCCYCOINNAME() {
		return CCYCOINNAME;
	}

	public void setCCYCOINNAME(String cCYCOINNAME) {
		CCYCOINNAME = cCYCOINNAME;
	}

	public int getCCYROUNDINGNO() {
		return CCYROUNDINGNO;
	}

	public void setCCYROUNDINGNO(int cCYROUNDINGNO) {
		CCYROUNDINGNO = cCYROUNDINGNO;
	}

	public int getCCYSTATUS() {
		return CCYSTATUS;
	}

	public void setCCYSTATUS(int cCYSTATUS) {
		CCYSTATUS = cCYSTATUS;
	}

	public Date getRECORDDATE() {
		return RECORDDATE;
	}

	public void setRECORDDATE(Date rECORDDATE) {
		RECORDDATE = rECORDDATE;
	}

}