package com.crosspay.payment.model;

import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;



@Entity
@Table(name = "LOGINS")
public class Logins {

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int LOGINS_ID;

	@NotNull
	private String LOGINKEY;

	@NotNull
	private Timestamp LOGINTIMESTAMP;

	@NotNull
	private int LOGINUSERID;

	@Null
	private String CUSTOMERNO;

	@NotNull
	private String LOGINIPADDRESS;

	@NotNull
	private Date LOGINDATE;

	@Null
	private String LOGINCLIENT;

	@NotNull
	private int LOGINSUCCESSATTEMPTNO;

	@NotNull
	private int LOGINSTATUS;

	@NotNull
	private int USERCATEGORY;

	// Public methods
	// Getter and setter methods

	public int getLOGINS_ID() {
		return LOGINS_ID;
	}

	public void setLOGINS_ID(int lOGINS_ID) {
		LOGINS_ID = lOGINS_ID;
	}

	public String getLOGINKEY() {
		return LOGINKEY;
	}

	public void setLOGINKEY(String lOGINKEY) {
		LOGINKEY = lOGINKEY;
	}

	public Timestamp getLOGINTIMESTAMP() {
		return LOGINTIMESTAMP;
	}

	public void setLOGINTIMESTAMP(Timestamp lOGINTIMESTAMP) {
		LOGINTIMESTAMP = lOGINTIMESTAMP;
	}

	public int getLOGINUSERID() {
		return LOGINUSERID;
	}

	public void setLOGINUSERID(int lOGINUSERID) {
		LOGINUSERID = lOGINUSERID;
	}

	public String getCUSTOMERNO() {
		return CUSTOMERNO;
	}

	public void setCUSTOMERNO(String cUSTOMERNO) {
		CUSTOMERNO = cUSTOMERNO;
	}

	public String getLOGINIPADDRESS() {
		return LOGINIPADDRESS;
	}

	public void setLOGINIPADDRESS(String lOGINIPADDRESS) {
		LOGINIPADDRESS = lOGINIPADDRESS;
	}

	public Date getLOGINDATE() {
		return LOGINDATE;
	}

	public void setLOGINDATE(Date lOGINDATE) {
		LOGINDATE = lOGINDATE;
	}

	public String getLOGINCLIENT() {
		return LOGINCLIENT;
	}

	public void setLOGINCLIENT(String lOGINCLIENT) {
		LOGINCLIENT = lOGINCLIENT;
	}

	public int getLOGINSUCCESSATTEMPTNO() {
		return LOGINSUCCESSATTEMPTNO;
	}

	public void setLOGINSUCCESSATTEMPTNO(int lOGINSUCCESSATTEMPTNO) {
		LOGINSUCCESSATTEMPTNO = lOGINSUCCESSATTEMPTNO;
	}

	public int getLOGINSTATUS() {
		return LOGINSTATUS;
	}

	public void setLOGINSTATUS(int lOGINSTATUS) {
		LOGINSTATUS = lOGINSTATUS;
	}

	public int getUSERCATEGORY() {
		return USERCATEGORY;
	}

	public void setUSERCATEGORY(int uSERCATEGORY) {
		USERCATEGORY = uSERCATEGORY;
	}

}